[package]
name = "memri_ocr"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
tracing = "0.1"
windows = { version = "0.58", features = [
    "Globalization",
    "Media_Ocr",
    "Graphics_Imaging",
    "Storage_Streams",
    "Foundation",
    "implement",
] }
